"""Add missing subscription fields

Revision ID: 59be0754d297
Revises: c143178f0fba
Create Date: 2025-12-30 17:35:05.128057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '59be0754d297'
down_revision: Union[str, Sequence[str], None] = 'c143178f0fba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meal_plans', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('meal_plans', sa.Column('image_file_paths', sa.JSON(), nullable=True))
    op.alter_column('meal_plans', 'target_goal',
               existing_type=postgresql.ARRAY(sa.VARCHAR(length=50)),
               type_=sa.JSON(),
               nullable=True,
               postgresql_using='array_to_json(target_goal)')
    op.alter_column('meal_plans', 'calories_range',
               existing_type=postgresql.ARRAY(sa.BIGINT()),
               type_=sa.JSON(),
               nullable=True,
               postgresql_using='array_to_json(calories_range)')
    op.alter_column('meal_plans', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('meal_plans', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.add_column('notifications', sa.Column('title', sa.String(length=200), nullable=True))
    op.alter_column('notifications', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('notifications', 'scheduled_for',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('notifications', 'sent_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('notifications', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_notifications_scheduled_for'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_status'), table_name='notifications')
    op.add_column('subscriptions', sa.Column('yookassa_subscription_id', sa.String(length=255), nullable=True))
    op.add_column('subscriptions', sa.Column('currency', sa.String(length=3), nullable=True))
    op.alter_column('subscriptions', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('subscriptions', 'activated_by_admin',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('subscriptions', 'activated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('subscriptions', 'starts_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('subscriptions', 'ends_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('subscriptions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_subscriptions_ends_at'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_status'), table_name='subscriptions')
    op.add_column('user_daily_logs', sa.Column('workout_feedback', sa.Text(), nullable=True))
    op.add_column('user_daily_logs', sa.Column('meal_feedback', sa.Text(), nullable=True))
    op.alter_column('user_daily_logs', 'date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Date(),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_DATE'))
    op.alter_column('user_daily_logs', 'workout_completed',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('user_daily_logs', 'meal_plan_followed',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('user_daily_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_user_daily_logs_date'), table_name='user_daily_logs')
    op.alter_column('user_profiles', 'is_experienced_training',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('user_profiles', 'last_ideal_form_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Date(),
               existing_nullable=True)
    op.alter_column('user_profiles', 'profile_completed',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('user_profiles', 'completed_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('user_profiles', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_user_profiles_profile_completed'), table_name='user_profiles')
    op.drop_constraint(op.f('user_profiles_user_id_key'), 'user_profiles', type_='unique')
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'is_blocked',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_users_telegram_id'), table_name='users')
    op.create_unique_constraint(None, 'users', ['telegram_id'])
    op.add_column('workout_plans', sa.Column('target_body_type', sa.JSON(), nullable=True))
    op.add_column('workout_plans', sa.Column('video_links', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('workout_plans', sa.Column('created_by_admin', sa.UUID(), nullable=True))
    op.alter_column('workout_plans', 'target_goal',
               existing_type=postgresql.ARRAY(sa.VARCHAR(length=50)),
               type_=sa.JSON(),
               nullable=True,
               postgresql_using='array_to_json(target_goal)')
    op.alter_column('workout_plans', 'target_level',
               existing_type=postgresql.ARRAY(sa.VARCHAR(length=50)),
               type_=sa.JSON(),
               nullable=True,
               postgresql_using='array_to_json(target_level)')
    op.alter_column('workout_plans', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('workout_plans', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_workout_plans_is_active'), table_name='workout_plans')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_workout_plans_is_active'), 'workout_plans', ['is_active'], unique=False)
    op.alter_column('workout_plans', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('workout_plans', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('workout_plans', 'target_level',
               existing_type=sa.JSON(),
               type_=postgresql.ARRAY(sa.VARCHAR(length=50)),
               nullable=False)
    op.alter_column('workout_plans', 'target_goal',
               existing_type=sa.JSON(),
               type_=postgresql.ARRAY(sa.VARCHAR(length=50)),
               nullable=False)
    op.drop_column('workout_plans', 'created_by_admin')
    op.drop_column('workout_plans', 'video_links')
    op.drop_column('workout_plans', 'target_body_type')
    op.drop_constraint(None, 'users', type_='unique')
    op.create_index(op.f('ix_users_telegram_id'), 'users', ['telegram_id'], unique=True)
    op.alter_column('users', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'is_blocked',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.create_unique_constraint(op.f('user_profiles_user_id_key'), 'user_profiles', ['user_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_user_profiles_profile_completed'), 'user_profiles', ['profile_completed'], unique=False)
    op.alter_column('user_profiles', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('user_profiles', 'completed_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('user_profiles', 'profile_completed',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('user_profiles', 'last_ideal_form_date',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('user_profiles', 'is_experienced_training',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.create_index(op.f('ix_user_daily_logs_date'), 'user_daily_logs', ['date'], unique=False)
    op.alter_column('user_daily_logs', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('user_daily_logs', 'meal_plan_followed',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('user_daily_logs', 'workout_completed',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('user_daily_logs', 'date',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_DATE'))
    op.drop_column('user_daily_logs', 'meal_feedback')
    op.drop_column('user_daily_logs', 'workout_feedback')
    op.create_index(op.f('ix_subscriptions_status'), 'subscriptions', ['status'], unique=False)
    op.create_index(op.f('ix_subscriptions_ends_at'), 'subscriptions', ['ends_at'], unique=False)
    op.alter_column('subscriptions', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('subscriptions', 'ends_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('subscriptions', 'starts_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('subscriptions', 'activated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('subscriptions', 'activated_by_admin',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('subscriptions', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.drop_column('subscriptions', 'currency')
    op.drop_column('subscriptions', 'yookassa_subscription_id')
    op.create_index(op.f('ix_notifications_status'), 'notifications', ['status'], unique=False)
    op.create_index(op.f('ix_notifications_scheduled_for'), 'notifications', ['scheduled_for'], unique=False)
    op.alter_column('notifications', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('notifications', 'sent_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('notifications', 'scheduled_for',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('notifications', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.drop_column('notifications', 'title')
    op.alter_column('meal_plans', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('meal_plans', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('meal_plans', 'calories_range',
               existing_type=sa.JSON(),
               type_=postgresql.ARRAY(sa.BIGINT()),
               nullable=False)
    op.alter_column('meal_plans', 'target_goal',
               existing_type=sa.JSON(),
               type_=postgresql.ARRAY(sa.VARCHAR(length=50)),
               nullable=False)
    op.drop_column('meal_plans', 'image_file_paths')
    op.drop_column('meal_plans', 'description')
    # ### end Alembic commands ###
